name: "nubank"
description: Just another study project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  android_disable_fullscreen: true
  image: images/logo.png
  color: "9c27b0"

flutter_icons:
  image_path: "images/favicon.png"
  adaptive_icon_background: "#9c27b0"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
